apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: kube-ebpf
  labels:
    app: kube-ebpf
spec:
  selector:
    matchLabels:
      name: kube-ebpf
  template:
    metadata:
      labels:
        name: kube-ebpf
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/path: '/'
        prometheus.io/port: '8000'
    spec:
      containers:
        - name: kube-ebpf
          image: ghcr.io/mrsupiri/kube-ebpf:latest
          ports:
            - containerPort: 8000
              name: metrics
          imagePullPolicy: Always
          resources:
            requests:
              ephemeral-storage: "2Gi"
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: PYTHONUNBUFFERED
              value: "1"
          securityContext:
            privileged: true
            capabilities:
              add:
                - SYS_ADMIN
          volumeMounts:
            - name: modules-dir
              mountPath: /lib/modules
              readOnly: false
            - name: linux-headers-generated
              mountPath: /usr/src/
              readOnly: false
            - name: debug
              mountPath: /sys/kernel/debug
              readOnly: false
      hostNetwork: true
      hostPID: true
      serviceAccountName: kube-ebpf
      initContainers:
        - name: init-headers
          image: ghcr.io/mrsupiri/kube-ebpf/init-headers:latest
          imagePullPolicy: IfNotPresent
          securityContext:
            privileged: true
            capabilities:
              add: ["SYS_ADMIN"]
          volumeMounts:
            - name: lsb-release
              mountPath: /etc/lsb-release.host
              readOnly: false
            - name: os-release
              mountPath: /etc/os-release.host
              readOnly: false
            - name: modules-dir
              mountPath: /lib/modules
              readOnly: false
            - name: modules-host
              mountPath: /lib/modules.host
              readOnly: false
            - name: linux-headers-generated
              mountPath: /usr/src/
              readOnly: false
            - name: boot-host
              mountPath: /boot.host
              readOnly: false
      volumes:
        - name: lsb-release
          hostPath:
            path: /etc/lsb-release
        - name: os-release
          hostPath:
            path: /etc/os-release
        - name: modules-dir
          hostPath:
            path: /var/cache/linux-headers/modules_dir
        - name: linux-headers-generated
          hostPath:
            path: /var/cache/linux-headers/generated
        - name: boot-host
          hostPath:
            path: /
        - name: modules-host
          hostPath:
            path: /lib/modules
        - name: debug
          hostPath:
            path: /sys/kernel/debug
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kube-ebpf
rules:
  - apiGroups: [""]
    resources:
      - services
      - pods
      - nodes
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kube-ebpf
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kube-ebpf
subjects:
  - kind: ServiceAccount
    name: kube-ebpf
    namespace: default
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kube-ebpf